// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMg7mQxHOZ4r17mKGEbgxZLo0GAVjAIY',
    appId: '1:929318443424:web:f332360a0f82370a236cc5',
    messagingSenderId: '929318443424',
    projectId: 'nosql-db-mobileapp',
    authDomain: 'nosql-db-mobileapp.firebaseapp.com',
    storageBucket: 'nosql-db-mobileapp.firebasestorage.app',
    measurementId: 'G-DK0NRLKBVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESoXFMyAlzZb74PzOldmDwO6TOaKqO5c',
    appId: '1:929318443424:android:683c565d08d0e03b236cc5',
    messagingSenderId: '929318443424',
    projectId: 'nosql-db-mobileapp',
    storageBucket: 'nosql-db-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUldxqzTGFyEUiEcPKoj2mDaqRDmqYzuM',
    appId: '1:929318443424:ios:e60691aeb97861f9236cc5',
    messagingSenderId: '929318443424',
    projectId: 'nosql-db-mobileapp',
    storageBucket: 'nosql-db-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );
}
